import Head from "next/head";
import Image from "next/image";

import ProjectMenu from "../components/ProjectMenu";

import styles from "../styles/project.module.css";
import Container from "../components/Container";

export default function Flynet() {
  const color = "#bf2431";
  if (typeof window !== "undefined") {
    document.documentElement.style.setProperty("--Scrollbar-color", color);
  }
  return (
    <>
      <Head>
        <title>Flynet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className={styles.section}>
        <ProjectMenu
          githubLink="https://github.com/Gr3it/Servlet-Flynet"
          github
        />
        <Container type="large">
          <div className={styles.home}>
            <h2 className={styles.subtitle}>Flynet</h2>
            <h1 className={styles.title}>
              Cagliari airport website: flights' info and administration page
            </h1>
            <div
              onClick={() => {
                document.getElementById("anchor-image").scrollIntoView();
              }}
              className={styles["explore-container"]}
            >
              <h2 className={styles["explore-text"]}>Explore more</h2>
              <svg
                className={styles["explore-svg"]}
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 448 512"
              >
                <path
                  fill="currentColor"
                  d="M413.1 222.5l22.2 22.2c9.4 9.4 9.4 24.6 0 33.9L241 473c-9.4 9.4-24.6 9.4-33.9 0L12.7 278.6c-9.4-9.4-9.4-24.6 0-33.9l22.2-22.2c9.5-9.5 25-9.3 34.3.4L184 343.4V56c0-13.3 10.7-24 24-24h32c13.3 0 24 10.7 24 24v287.4l114.8-120.5c9.3-9.8 24.8-10 34.3-.4z"
                ></path>
              </svg>
            </div>
          </div>
        </Container>
        <div
          className={styles["first-image"]}
          style={{ backgroundColor: color }}
        >
          <Container type="large">
            <div
              id="anchor-image"
              style={{ position: "absolute", top: "-6.875rem", left: 0 }}
            ></div>
            <Image
              src={"/images/Flynet/Home.jpg"}
              alt="Site Homepage"
              width="2543"
              height="1287"
            />
          </Container>
        </div>
        <Container type="large">
          <div className={styles.section}>
            <div className={styles.description}>
              <h1 className={styles["section-title"]} style={{ width: "100%" }}>
                The challenge
              </h1>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "100%" }}
              >
                The site reads the flight's data from a MySQL database and
                displays the relevant information on different pages. Moreover,
                it has to provide an administrative page, accessible by the
                airport's staff via login, for them to manage the flight
                database. The homepage will display useful information for the
                customer, like maps and Cagliari's weather forecast.
              </p>
            </div>
          </div>
        </Container>
        <div
          className={styles["presentation-images"]}
          style={{ backgroundColor: color }}
        >
          <div className={styles["grid-image-container"]}>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Home.jpg"}
                alt="Home"
                width="2543"
                height="1287"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Arrivals.jpg"}
                alt="Arrivals"
                width="2543"
                height="1287"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Login.jpg"}
                alt="Login"
                width="2543"
                height="1287"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Maps.jpg"}
                alt="Maps"
                width="2543"
                height="1287"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Search.jpg"}
                alt="Search"
                width="2543"
                height="1287"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/Flynet/Admin.jpg"}
                alt="Admin"
                width="2543"
                height="1287"
              />
            </div>
          </div>
        </div>
        <Container type="large">
          <div className={styles.section}>
            <div className={styles.description}>
              <h1 className={styles["section-title"]} style={{ width: "100%" }}>
                The pages
              </h1>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "100%" }}
              >
                The website is based on three main pages: the airport flight
                arrival and departures pages, the flight search page, and the
                administrative page for the airport's staff. The user can
                navigate through these pages with a practical menu positioned at
                the top.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image-dual"]}
                style={{ backgroundColor: color }}
              >
                <div className={styles["image-dual"]}>
                  <Image
                    src={"/images/Flynet/Arrivals.jpg"}
                    alt="Arrivals Page"
                    width="2543"
                    height="1287"
                  />
                </div>
                <div className={styles["image-dual"]}>
                  <Image
                    src={"/images/Flynet/Departures.jpg"}
                    alt="Departures Page"
                    width="2543"
                    height="1287"
                  />
                </div>
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                The airport flight arrival and departures pages are very
                similar. They show the flights arriving and departing time by
                reading the relevant data from the database. The data are
                displayed in a user-friendly table that highlights the row where
                the cursor is.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/Flynet/Search.jpg"}
                  alt="Search Page"
                  width="2543"
                  height="1287"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                On the flight search page, the user can view all flights from
                and to a selected destination by clicking on the button at the
                top left of the screen. Meanwhile, the section on the top right
                of the page allows the user to search flights through a flight
                code or airport code.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/Flynet/Admin.jpg"}
                  alt="Admin Page"
                  width="2543"
                  height="1287"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                The administrative page is reserved for the staff only. It
                requires logging in with a valid account to edit the data stored
                in the database. Through multiple forms, the airport's staff can
                add a new flight, add a new flight company, edit an existing
                flight, delete an existing flight.
              </p>
            </div>
          </div>
        </Container>
      </div>
    </>
  );
}
