import Head from "next/head";
import Image from "next/image";

import ProjectMenu from "../components/ProjectMenu";

import styles from "../styles/project.module.css";
import Container from "../components/Container";

export default function HotelMeano() {
  const color = "#fd871f";
  if (typeof window !== "undefined") {
    document.documentElement.style.setProperty("--Scrollbar-color", color);
  }
  return (
    <>
      <Head>
        <title>Hotel Meano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className={styles.section}>
        <ProjectMenu
          githubLink="https://github.com/Gr3it/School-Elaborate"
          webSiteLink="https://hotelmeano.altervista.org/"
          github
          webSite
        />
        <Container type="large">
          <div className={styles.home}>
            <h2 className={styles.subtitle}>Hotel Meano</h2>
            <h1 className={styles.title}>
              Presentation of the hotel and implementation of a booking system
            </h1>
            <div
              onClick={() => {
                document.getElementById("anchor-image").scrollIntoView();
              }}
              className={styles["explore-container"]}
            >
              <h2 className={styles["explore-text"]}>Explore more</h2>
              <svg
                className={styles["explore-svg"]}
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 448 512"
              >
                <path
                  fill="currentColor"
                  d="M413.1 222.5l22.2 22.2c9.4 9.4 9.4 24.6 0 33.9L241 473c-9.4 9.4-24.6 9.4-33.9 0L12.7 278.6c-9.4-9.4-9.4-24.6 0-33.9l22.2-22.2c9.5-9.5 25-9.3 34.3.4L184 343.4V56c0-13.3 10.7-24 24-24h32c13.3 0 24 10.7 24 24v287.4l114.8-120.5c9.3-9.8 24.8-10 34.3-.4z"
                ></path>
              </svg>
            </div>
          </div>
        </Container>
        <div
          className={styles["first-image"]}
          style={{ backgroundColor: color }}
        >
          <Container type="large">
            <div
              id="anchor-image"
              style={{ position: "absolute", top: "-6.875rem", left: 0 }}
            ></div>
            <Image
              src={"/images/HotelMeano/Home.jpg"}
              alt="Site Homepage"
              width="1903"
              height="927"
            />
          </Container>
        </div>
        <Container type="large">
          <div className={styles.section}>
            <div className={styles.description}>
              <h1 className={styles["section-title"]} style={{ width: "100%" }}>
                The challenge
              </h1>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "100%" }}
              >
                The goal of this project was to develop a website and redesign
                the network infrastructures for a hotel based in the small town
                of Meano, nearby Trento. We were asked to create the main
                webpage of the hotel, which had to show the hotel’s building and
                include the services offered to the guests as well as room
                prices and contact information. The network infrastructure
                required to be designed across two locations: the hotel and the
                office building. The most important request for the website was
                to conceive a system through which customers could make a
                reservation online. An additional directive was to implement an
                advanced Wifi system both for the hotel’s guests and offices.
              </p>
            </div>
          </div>
        </Container>
        <div
          className={styles["presentation-images"]}
          style={{ backgroundColor: color }}
        >
          <div className={styles["grid-image-container"]}>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/Contact.png"}
                alt="Contact"
                width="1903"
                height="381"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/Proposals.jpg"}
                alt="Proposals"
                width="1903"
                height="772"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/Activities.jpg"}
                alt="Activities"
                width="1903"
                height="928"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/PhotoGallery.jpg"}
                alt="PhotoGallery"
                width="1903"
                height="694"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/Prices.jpg"}
                alt="Prices"
                width="1903"
                height="841"
              />
            </div>
            <div className={styles.image}>
              <Image
                src={"/images/HotelMeano/About.jpg"}
                alt="About"
                width="1903"
                height="556"
              />
            </div>
          </div>
        </div>
        <Container type="large">
          <div className={styles.section}>
            <div className={styles.description}>
              <h1 className={styles["section-title"]} style={{ width: "100%" }}>
                The booking page
              </h1>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "100%" }}
              >
                This page leads the customer through the multiple-step process
                of making a reservation. The four-step process is presented in
                the following section.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/HotelMeano/Page1.jpg"}
                  alt="Date Selection"
                  width="1903"
                  height="928"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                The guest is first asked to select the desired length of stay.
                This information is used by the system to show which rooms are
                available for the booking.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/HotelMeano/Page2.jpg"}
                  alt="Room Selection"
                  width="1903"
                  height="1170"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                The next page will lead to a 3D map of the hotel displaying
                which rooms are available for a reservation and which ones are
                already booked. The customer can select and deselect the rooms
                of interest by interacting with the map.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/HotelMeano/Page3.jpg"}
                  alt="Personal Data Registration"
                  width="1903"
                  height="928"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                Once selected the desired room, the guest is asked to fill in
                their personal information relevant for the finalizing of the
                booking, such as name, surname, ID information, and email. The
                data will be stored in the hotel database.
              </p>
            </div>
            <div className={styles.row}>
              <div
                className={styles["row-image"]}
                style={{ backgroundColor: color }}
              >
                <Image
                  src={"/images/HotelMeano/Page4.jpg"}
                  alt="Receipt Page"
                  width="1903"
                  height="928"
                />
              </div>
              <p
                className={styles["paragraph-justify"]}
                style={{ width: "50%" }}
              >
                At the last step, the total amount and details of the
                reservation are presented to the customer. The information for
                paying the deposit, which is used as a confirmation of the
                booking is provided.
              </p>
            </div>
          </div>
        </Container>
      </div>
    </>
  );
}
